### PR TITLE
Placeholder for other webhook events implementation.

### PR DESCRIPTION
**Pull request by yellowred**

### CODE REVIEW

**Comment by yellowred** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #36** <a href="https://app.graphite.dev/github/pr/lightsparkdev/lightspark-rs/36?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/lightsparkdev/lightspark-rs/36?utm_source=stack-comment).

**Comment by zhenlu** [comment]
Does the force closure webhook need to go through remote signing flow? or is it just informational?

**Comment by yellowred** [comment]
> Does the force closure webhook need to go through remote signing flow? or is it just informational?

FC webhook is a separate webhook as other, like payment finished, etc. But the url for all webhooks is the same, so this endpoint handler should be able to distinguish other webhooks and handle them separately from signing flow. This why this `match` added, but also to allow FC webhooks from Sparkcore to resolve and stop bugging me :)

**Comment by zhenlu** [comment]
I see. LGTM!

**Review by zhenlu — APPROVED** [review]

**Comment by yellowred** [comment]
### Merge activity

* **Feb 5, 8:07 PM EST**: @yellowred merged this pull request with [Graphite](https://app.graphite.dev/github/pr/lightsparkdev/lightspark-rs/36).

**Pull request merged**
